### PR TITLE
docs: Title case for headings

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by laymonage** [comment]
It's more of a stylistic decision, tbh 😕

**Comment by nschonni** [comment]
Yes, the 2 main styles are either, every word is capitalized, or only the first word, or all words https://www.thoughtco.com/title-case-capitalization-1692469
Sentences or headings don't usually start with a lower case letter

**Comment by laymonage** [comment]
> Yes, the 2 main styles are either, every word is capitalized, or only the first word, or all words https://www.thoughtco.com/title-case-capitalization-1692469 Sentences or headings don't usually start with a lower case letter

I mean, I do know that, but it was a deliberate stylistic decision.

Anyway, if we want to go through with this, please change all the other markdown files (`ADVANCED-USAGE.md`, `CHANGELOG.md`, `CONTRIBUTING.md`, `SELF-HOSTING.md`, and all the translations for `README.md`).

**Comment by nschonni** [comment]
OK, I'll try and make the changes later today. It was one of the translations that made me notice it 😄 , but I'm also OK with just closing this if you prefer it as-is

**Comment by laymonage** [comment]
I suppose it helps with readability, so let's proceed.

**Comment by nschonni** [comment]
@laymonage I think I got them all, but I'm not sure for the Korean or Chinese characters

**Comment by laymonage** [comment]
I don't think there's lowercase/uppercase distinction in CJK languages, so it should be okay.

**Pull request merged**
