### PR TITLE
docs: minor update for README.ko.md

### PR DESCRIPTION
**Pull request by JeukHwang**
- [x] Solve minor Korean grammar issue
- [x] Try to match the content of the original English text

### CODE REVIEW

**Comment by JeukHwang** [comment]
If Korean maintainer exists, I think it's a good idea to double-check and share ideas with them.

**Comment by JeukHwang** [comment]
@dodok8 Mention the first contributor to the Korean localization.

**Comment by dodok8** [comment]
LGTM. Much better translation.

**Comment by JeukHwang** [comment]
Thank you for sharing your thoughts. Have a nice day 😊

**Comment by laymonage** [comment]
감사!

**Pull request merged**
