### PR TITLE
Add the `data-callback` attribute

### LINKED ISSUE #850: How to aware the comments <iframe> was loaded?
Hi, I want to change the theme at runtime, but I got the following error when loading the iframe lazily (`loading="lazy"`).

```log
index.ts:13 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://giscus.app') does not match the recipient window's origin ('http://localhost:13131').
```

So I'm wondering if there is an option to add the `onload` attribute on the `<iframe>`, so that I could be aware when is the iframe is ready to change theme.

### PR DESCRIPTION
**Pull request by razonyang**
Fixed #850

### CODE REVIEW

**Review by lukethacoder — APPROVED** [review]

**Comment by lukethacoder** [comment]
Keen to see this one merged in

**Review by Aqours — APPROVED** [review]

**Review by laymonage — COMMENTED** [review]
Thanks, but inline scripts are a bad idea for security and other reasons. I'd much rather dispatch a custom `Event` that your code can listen to.

**Comment by YexuanXiao** [comment]
@laymonage Can a message be sent to the parent window after gitcus is successfully loaded? This is a useful feature.

**Comment by YexuanXiao** [comment]
I use the following code to detect if giscus is loaded:
```javascript
const element = document.querySelector('div.giscus');
const observer = new MutationObserver((mutationsList, observer) => {
    for (const record of mutationsList) {
        if (record.type !== 'childList') continue;
        const iframe = record.addedNodes[0];
        iframe.addEventListener('load', () => {
            changeTheme()
            // and event bingdings here
            observer.disconnect()
        })
    }
});
observer.observe(element, { childList: true, subtree: true });
```

**Pull request closed without merging**
