### PR TITLE
Add Catppuccin themes

### PR DESCRIPTION
**Pull request by uncenter**
Adds the https://catppuccin.com/ theme (upstreamed from https://github.com/catppuccin/giscus).

### CODE REVIEW

**Comment by uncenter** [comment]
I'd like to make note that having to add a locale translation for even unsupported languages is a bit redundant. Would it be possible to update the i18n implementation to default to English if a key doesn't exist for a different language?

**Review by laymonage — APPROVED** [review]
Thanks, I tweaked the opacity/lightness of some of the colors to improve the contrast to meet accessibility requirements, hope that's OK.

**Comment by laymonage** [comment]
> I'd like to make note that having to add a locale translation for even unsupported languages is a bit redundant. Would it be possible to update the i18n implementation to default to English if a key doesn't exist for a different language?

I'd love to but I don't think the library we use has an easy way to do it, or maybe I missed it.

**Comment by uncenter** [comment]
> Thanks, I tweaked the opacity/lightness of some of the colors to improve the contrast to meet accessibility requirements, hope that's OK.

That's fine, ideally you could make those changes in our template https://github.com/catppuccin/giscus/blob/main/src/base.css though and then update them here.

**Pull request merged**
