### PR TITLE
Add comments count endpoint

### LINKED ISSUE #145: Get the number of comments outside of the blog page
I would like to get the number of comments in a blog to show something like this:

the number of comments in the post

This is a good feature to have.
When looking at the comments counter, I just see a link to the discussion in the repo.

### PR DESCRIPTION
**Pull request by typeofweb**
A custom API route for getting comment count. Useful for more advanced use-cases such as fetching & displaying the number of comments below each blogpost. 

Obviously, this is just a draft because there's plenty of repetitive code to `pages/api/discussions/index.ts`.

Fixes #145

### CODE REVIEW

**Comment by laymonage** [comment]
Hey, thanks for the PR.

However, before you continue working on this, I want to give a heads-up: I *might* not merge this. The reason is, well... this API would basically just be a proxy to GitHub's API. I'm trying to keep such endpoints to a minimum, to minimize the chance of giscus getting rate limited (it *has* happened before, see #188), or exceeding my Vercel monthly limits.

I mean, if GitHub provides a way to access the API without authentication (like the REST API), I would never even have `pages/api/discussions/index.ts` in the first place (at least the `GET` handler).

I do acknowledge that this endpoint could be useful, especially because the GraphQL API isn't very friendly. Maybe we could host such APIs separately (e.g. on Cloudflare Workers), or make this opt-in for those who self-host giscus...

**Comment by mmiszy** [comment]
Yes, I understand the issue. I think the solution might be to only enable it for self-hosted instances or (in the future) for paid accounts?

**Comment by laymonage** [comment]
> Yes, I understand the issue. I think the solution might be to only enable it for self-hosted instances

Yup, likely through an environment variable that's enabled/disabled by default (I don't mind which one), so I can configure it from my Vercel dashboard.

Next.js does not have a built-in functionality to exclude certain pages from the production build, though. We probably have to do it manually, for example with the following variable:

```
ADDITIONAL_PAGES=api/discussions/comments-count.tsx,api/some-other-api.ts
ENABLE_ADDITIONAL_PAGES=false
```

And then, write something in the build script so that if `ENABLE_ADDITIONAL_PAGES` is false, all the files specified in `ADDITIONAL_PAGES` will be removed before the build.

> or (in the future) for paid accounts?

I'm planning to keep it free for all users.

**Comment by laymonage** [comment]
This might be useful: https://nextjs.org/docs/api-reference/next.config.js/custom-page-extensions

We can rename existing pages to have `.page.tsx` extension and name these optional pages with an extension such as `.page.opt.tsx` and add `page.opt.tsx` to the `pageExtensions` config based on `process.env.ENABLE_ADDITIONAL_PAGES`.

**Comment by laymonage** [comment]
Closing due to inactivity.

**Pull request closed without merging**
