### PR TITLE
Add Gruvbox theme

### PR DESCRIPTION
**Pull request by michaelneuper**
Add the following gruvbox themes:
- Gruvbox dark
- Gruvbox light
- Gruvbox (adapts to `prefers-color-scheme`)

### CODE REVIEW

**Review by laymonage — CHANGES_REQUESTED** [review]
Thank you for the PR. Unfortunately, there are some contrast issues with the colours. Could you fix them please?

image

**Comment by ttycelery** [comment]
Would love to see this.

**Comment by michaelneuper** [comment]
> Thank you for the PR. Unfortunately, there are some contrast issues with the colours. Could you fix them please?

I've fixed the contrast issues, here is what is looks like now:

gruvbox-dark
gruvbox-light

**Review by laymonage — APPROVED** [review]
Thanks! I tweaked the accent `--color-neutral-muted` and `--color-accent-fg` colours to improve the accessibility of linked inline code, hope that's OK.

**Pull request merged**
