### PR TITLE
Persian translation

### PR DESCRIPTION
**Pull request by MEgooneh**
Has RTL been fixed?

### CODE REVIEW

**Comment by nschonni** [comment]
> Has RTL been fixed?

Think just discussed a little in https://github.com/giscus/giscus/pull/239 but probably needs it's own issue

**Comment by laymonage** [comment]
Some RTL improvements made in #626, if you could rebase this PR and add translations for the new strings since this PR was opened, I'll look into this again. Thanks!

**Comment by meissam** [comment]
Hey, I'd seen this before. I also create another PR for Persian Localization. 
I was wondering what was the final decision on this PR. Can we have it approved soon?

**Comment by laymonage** [comment]
Superseded by #867.

**Pull request closed without merging**
