### PR TITLE
Add Simplified Chinese(zh-Hans)

### PR DESCRIPTION
**Pull request by misitebao**
The use of `zh-CN` as the Simplified Chinese identifier is old usage, and now this identifier is added as many new Simplified Chinese websites are also gradually using `zh-Hans` as the language identifier. The content of the translation file is the same as `zh-CN`, the purpose is to satisfy all users who use Simplified Chinese.

Note: `zh-CN` is a usage with a regional identifier, generally referring to Chinese users, while `zh-Hans` does not carry a regional identifier and refers to all users who use Simplified Chinese.

### CODE REVIEW

**Comment by misitebao** [comment]
Another more personal reason is that I don't want to add extra judgment to my template syntax, which is rendered by the static site generator.

```javascript
    <script
      src="https://giscus.app/client.js"
      ......
      data-mapping="url"
      data-strict="0"
      data-reactions-enabled="1"
      data-emit-metadata="0"
      data-input-position="bottom"
      data-theme="{{ .Theme }}"
      data-lang="{{ .LanguageCode }}"
      crossorigin="anonymous"
      async
    ></script>
```

**Comment by ouuan** [comment]
> The use of `zh-CN` as the Simplified Chinese identifier is old usage

It's not "old usage". Actually, Wikipedia will ask you to choose from `zh-CN`, `zh-hk`, `zh-MO`, `zh-MY`, `zh-SG`, `zh-TW` if you are visiting `zh-Hans` or `zh-Hant`. The regional identifier is more specific than `Hans`/`Hant`, not "old usage".

I don't think file duplication is good, but it will be helpful if there are aliases to language codes.

**Comment by laymonage** [comment]
I added `zh-Hans` that fallbacks to `zh-CN` in #772 😄

**Comment by ouuan** [comment]
As `zh-Hans` -> `zh-CN` is added, `zh-Hant` -> `zh-TW` can also be added.

**Comment by laymonage** [comment]
Good call, added in #773.

**Pull request closed without merging**
