### PR TITLE
fix: emoji font-weight and font-family

### PR DESCRIPTION
**Pull request by zsdycs**
fix: #323

### CODE REVIEW

**Comment by zsdycs** [comment]
I noticed the "CHANGELOG.md" file.If there is no problem, I will add changes to the "CHANGELOG.md" file.

**Comment by laymonage** [comment]
Thanks! I'll take a look at this again later today.

> I noticed the "CHANGELOG.md" file. If there is no problem, I will add changes to the "CHANGELOG.md" file.

Feel free to do so, though I can also add it later when I make some small adjustments before merging.

**Comment by zsdycs** [comment]
Okay, from the [preview](https://giscus-git-fork-zsdycs-release-323-giscus.vercel.app), the problem has been resolved.

By the way, Merry Christmas. 🎄

**Comment by laymonage** [comment]
Thanks!

**Pull request merged**
