### PR TITLE
Improve Persian readme

### PR DESCRIPTION
**Pull request by Thecode764**
hi.

i remove a wrong text from persian readme for giscus

Before: `بدن`

After: `بدون`

بدن = `Body`
بدون = `Without`

Tnx

### CODE REVIEW

**Comment by Thecode764** [comment]
and i fixed some wrong text and i changed some persian words

**Comment by Thecode764** [comment]
@laymonage please check my pr

**Comment by Thecode764** [comment]
10 years later    ....

**Review by laymonage — COMMENTED** [review]
Thanks. I don't speak Farsi, so if you could get someone else who does to review your PR that would help a lot in the future.

**Comment by Thecode764** [comment]
thank you @laymonage

**Pull request merged**
