### PR TITLE
Create README.kh.md

### PR DESCRIPTION
**Pull request by nidexingg**
README of Khmer language

### CODE REVIEW

**Comment by laymonage** [comment]
Hey, thanks for the contribution but could you please combine this, #1165, #1166, and #1167 into a single PR instead of separate ones?

**Comment by nidexingg** [comment]
How to combine it? It's my first time to contribute to GitHub repo. Can you help me pls?

**Comment by nidexingg** [comment]
@laymonage , Can you check **[this forked repository](https://github.com/nidexingg/giscus.git)** that I've forked from giscus and I've uploaded and updated all the necessary files that need to be added for new language. Can you review and check that out?

**Comment by rustinwelter** [comment]
@nidexingg  

Assuming that the main branch in [your repository](https://github.com/nidexingg/giscus) only has all the changes related to the localization of your language, you probably just need to send a new pull request from it.

**Comment by nidexingg** [comment]
I've reopened a new pull request from my fork repo. Can you check that out?

**Comment by rustinwelter** [comment]
@nidexingg

I'm not the owner nor the maintainer of this repository so there's not much I can do about it really. You should wait until the maintainer checks if your PR is alright.

**Comment by nidexingg** [comment]
@rustinwelter Noted. Thank you anyway.

**Pull request closed without merging**
