### PR TITLE
Romanian translation for giscus

### PR DESCRIPTION
**Pull request by samarulmeu**

### CODE REVIEW

**Comment by laymonage** [comment]
Thanks @samarulmeu! The multi-language support feature isn't documented yet, but you should already be able to try this by adding `data-lang="ro"` to your `<script>` tag. I'm still working on adding the configuration step and updating the docs.

If there are updates to giscus that require new translations, I hope you don't mind if I ping you! :smile:

**Comment by samarulmeu** [comment]
Thank you so much, @laymonage! And do please ping me. I really have faith in this project and really want to use it on my blogs.

As a side note, is there a way to export the comments or backup them?

**Comment by samarulmeu** [comment]
@laymonage I will try it. I think that backup is very  important as, in the end, Discussions is **owned** by GitHub and accidents can happen (no access to the repository, suspended access, etc). Although I do not know if you can later import them in a new repository.

**Comment by laymonage** [comment]
@samarulmeu yeah, I agree on that.

Importing is possible, with a few caveats because the imported discussions and comments will be made as new ones. Some caveats I can think of right now:
1. Timestamps on the comment itself will be replaced by the timestamp of your import.
2. The comment author would be replaced by your username or your bot's username. There's no way to create a new comment on behalf of the actual author unless they explicitly give you the permission.
3. Links to other discussions/issues/PRs within the same repository may be broken?

Original information for (1) and (2) can still be shown by including it in the comment body, e.g.

> *On Oct 17, 2021, `@samarulmeu` wrote:*
> Actual comment body here

**Pull request merged**
