### PR TITLE
Add Simplified Chinese localization

### PR DESCRIPTION
**Pull request by meows6**

### CODE REVIEW

**Comment by laymonage** [comment]
Hi, thanks for the PR! Would you be willing to also translate the `README.md` into `README.zh-CN.md`?

**Comment by meows6** [comment]
> Hi, thanks for the PR! Would you be willing to also translate the `README.md` into `README.zh-CN.md`?

yes, I would,but it will take some time

**Comment by meows6** [comment]
> Hi, thanks for the PR! Would you be willing to also translate the `README.md` into `README.zh-CN.md`?

I already translate the `README.md` into `README.zh-CN.md`

**Comment by laymonage** [comment]
Superseded by #206.

**Pull request closed without merging**
